/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kohisop.gui;

import java.util.ArrayList;
import java.util.LinkedList;

import kohisop.Membership.Member;
import kohisop.model.MenuItem;
import kohisop.model.ItemPesanan;
import javax.swing.JOptionPane;

/**
 *
 * @author timbu
 */
public class Membership extends javax.swing.JFrame {

    /**
     * Creates new form Membership
     */
    private ArrayList<MenuItem> pesananDiterima;
    private Member currentMember;
    private LinkedList<Member> databaseMember;

    public Membership() {
        this(new ArrayList<>());
    }

    public Membership(ArrayList<MenuItem> pesananDiterima) {
        this.pesananDiterima = pesananDiterima;
        this.currentMember = null;
        this.databaseMember = new LinkedList<>();
        initDatabaseMember();
        initComponents();
        isiTabelPesanan();
    }

    // Initialize database member untuk testing
    private void initDatabaseMember() {
        databaseMember.add(new Member("John Doe", "A12345"));
        databaseMember.add(new Member("Jane Smith", "B54321"));
        databaseMember.add(new Member("Alex Brown", "ABCDEF"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        labelTitle = new javax.swing.JLabel();
        checkBoxBukanSebagaiMember = new javax.swing.JCheckBox();
        labelAturPesanan = new javax.swing.JLabel();
        buttonDaftarMember = new javax.swing.JButton();
        labelMembership = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaMethod = new javax.swing.JTextArea();
        checkBoxPunyaKode = new javax.swing.JCheckBox();
        labelPoin = new javax.swing.JLabel();
        textFieldMasukkanKode = new javax.swing.JTextField();
        buttonCariMember = new javax.swing.JButton();
        checkBoxDaftarMemberBaru = new javax.swing.JCheckBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelAturPesanan = new javax.swing.JTable();
        textFieldMasukkanNama = new javax.swing.JTextField();
        labelMasukkanNama = new javax.swing.JLabel();
        buttonLanjutkanPembayaran = new javax.swing.JButton();
        buttonTambahQty = new javax.swing.JButton();
        buttonKurangQty = new javax.swing.JButton();
        labelAturQty = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitle.setText("KohiSop");

        checkBoxBukanSebagaiMember.setText("Tidak Sebagai Member?");

        labelAturPesanan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelAturPesanan.setText("Atur Pesanan");

        buttonDaftarMember.setText("Daftar Member");
        buttonDaftarMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDaftarMemberActionPerformed(evt);
            }
        });

        labelMembership.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelMembership.setText("Membership");

        textAreaMethod.setColumns(20);
        textAreaMethod.setRows(5);
        jScrollPane1.setViewportView(textAreaMethod);

        checkBoxPunyaKode.setText("Punya Kode?");
        checkBoxPunyaKode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxPunyaKodeActionPerformed(evt);
            }
        });

        labelPoin.setText("Poin :");

        textFieldMasukkanKode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldMasukkanKode.setText("Masukan Kode di sini");

        buttonCariMember.setText("Cari Member");
        buttonCariMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCariMemberActionPerformed(evt);
            }
        });

        checkBoxDaftarMemberBaru.setText("Daftar Sebagai Member Baru");

        tabelAturPesanan.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {null, null, null, null, null, null},
                    {null, null, null, null, null, null},
                    {null, null, null, null, null, null},
                    {null, null, null, null, null, null}
                },
                new String[]{
                    "Kode", "Nama", "Kategori", "Harga", "Max. Qty", "Qty"
                }
        ));
        jScrollPane3.setViewportView(tabelAturPesanan);

        textFieldMasukkanNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldMasukkanNamaActionPerformed(evt);
            }
        });

        labelMasukkanNama.setText("Nama:");

        buttonLanjutkanPembayaran.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonLanjutkanPembayaran.setText("Lanjutkan ke Pembayaran");
        buttonLanjutkanPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLanjutkanPembayaranActionPerformed(evt);
            }
        });

        labelAturQty.setText("Atur Qty:");

        buttonTambahQty.setText("+");
        buttonTambahQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahQtyActionPerformed(evt);
            }
        });

        buttonKurangQty.setText("-");
        buttonKurangQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKurangQtyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(buttonLanjutkanPembayaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 680, Short.MAX_VALUE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(labelAturQty)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(buttonTambahQty, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(10, 10, 10)
                                                                                .addComponent(buttonKurangQty, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(6, 6, 6)
                                                                .addComponent(labelAturPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(labelMembership, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(checkBoxPunyaKode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(textFieldMasukkanKode)
                                                        .addComponent(buttonDaftarMember, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(11, 11, 11)
                                                                .addComponent(labelMasukkanNama, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(textFieldMasukkanNama, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                                        .addComponent(checkBoxDaftarMemberBaru)
                                                        .addComponent(checkBoxBukanSebagaiMember)
                                                        .addComponent(labelPoin)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(28, 28, 28)
                                                                .addComponent(buttonCariMember, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(labelMembership, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labelAturPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(10, 10, 10)
                                                .addComponent(labelAturQty)
                                                .addGap(5, 5, 5)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(buttonTambahQty)
                                                        .addComponent(buttonKurangQty)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(checkBoxPunyaKode)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textFieldMasukkanKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(buttonCariMember)
                                                .addGap(37, 37, 37)
                                                .addComponent(checkBoxDaftarMemberBaru)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(textFieldMasukkanNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(labelMasukkanNama))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(buttonDaftarMember)
                                                .addGap(38, 38, 38)
                                                .addComponent(checkBoxBukanSebagaiMember)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(labelPoin)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonLanjutkanPembayaran, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void checkBoxPunyaKodeActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void buttonCariMemberActionPerformed(java.awt.event.ActionEvent evt) {
        String kode = textFieldMasukkanKode.getText().trim();

        if (kode.isEmpty() || kode.equals("Masukan Kode di sini")) {
            JOptionPane.showMessageDialog(this, "Masukkan kode member terlebih dahulu!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Member found = cariMemberByKode(kode);
        if (found != null) {
            currentMember = found;
            JOptionPane.showMessageDialog(this,
                    "Selamat datang, " + found.getNama() + "!\nPoin Anda: " + found.getPoin(),
                    "Member Ditemukan", JOptionPane.INFORMATION_MESSAGE);
            textAreaMethod.setText("Member: " + found.getNama() + "\nKode: " + found.getKodeMember() + "\nPoin: " + found.getPoin());
        } else {
            JOptionPane.showMessageDialog(this, "Member tidak ditemukan!", "Error", JOptionPane.ERROR_MESSAGE);
            currentMember = null;
        }
    }

    private void textFieldMasukkanNamaActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void buttonDaftarMemberActionPerformed(java.awt.event.ActionEvent evt) {
        String nama = textFieldMasukkanNama.getText().trim();

        if (nama.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukkan nama terlebih dahulu!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Member newMember = new Member(nama);
        databaseMember.add(newMember);
        currentMember = newMember;

        JOptionPane.showMessageDialog(this,
                "Berhasil mendaftar!\nNama: " + newMember.getNama() + "\nKode: " + newMember.getKodeMember(),
                "Registrasi Member", JOptionPane.INFORMATION_MESSAGE);

        textAreaMethod.setText("Member: " + newMember.getNama() + "\nKode: " + newMember.getKodeMember() + "\nPoin: " + newMember.getPoin());
        textFieldMasukkanNama.setText("");
    }

    private void buttonLanjutkanPembayaranActionPerformed(java.awt.event.ActionEvent evt) {
        // Hitung total belanja dari tabel
        double totalBelanja = hitungTotalBelanja();

        if (totalBelanja <= 0) {
            JOptionPane.showMessageDialog(this, "Pesanan kosong!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Create ItemPesanan list with quantities from table
        ArrayList<ItemPesanan> pesananItems = new ArrayList<>();
        for (int i = 0; i < tabelAturPesanan.getRowCount(); i++) {
            int qty = 0;
            try {
                qty = Integer.parseInt(tabelAturPesanan.getValueAt(i, 5).toString());
            } catch (NumberFormatException e) {
                qty = 0;
            }

            if (qty > 0) {
                MenuItem item = pesananDiterima.get(i);
                ItemPesanan itemPesanan = new ItemPesanan(item, qty);
                pesananItems.add(itemPesanan);
            }
        }

        // Buka halaman Pembayaran dan pass data
        Pembayaran pembayaran = new Pembayaran(currentMember, pesananItems, totalBelanja);
        pembayaran.setVisible(true);

        // Close Membership window
        this.dispose();
    }

    private void buttonTambahQtyActionPerformed(java.awt.event.ActionEvent evt) {
        int selectedRow = tabelAturPesanan.getSelectedRow();
        if (selectedRow >= 0) {
            int currentQty = (int) tabelAturPesanan.getValueAt(selectedRow, 5);
            int maxQty = (int) tabelAturPesanan.getValueAt(selectedRow, 4);

            if (currentQty < maxQty) {
                tabelAturPesanan.setValueAt(currentQty + 1, selectedRow, 5);
            }
        }
    }

    private void buttonKurangQtyActionPerformed(java.awt.event.ActionEvent evt) {
        int selectedRow = tabelAturPesanan.getSelectedRow();
        if (selectedRow >= 0) {
            int currentQty = (int) tabelAturPesanan.getValueAt(selectedRow, 5);

            if (currentQty > 0) {
                tabelAturPesanan.setValueAt(currentQty - 1, selectedRow, 5);
            }
        }
    }

    private void setColumnWidths() {
        tabelAturPesanan.getColumnModel().getColumn(0).setPreferredWidth(70);   // Kode
        tabelAturPesanan.getColumnModel().getColumn(1).setPreferredWidth(180);  // Nama (diperlebar)
        tabelAturPesanan.getColumnModel().getColumn(2).setPreferredWidth(150);  // Kategori (diperlebar)
        tabelAturPesanan.getColumnModel().getColumn(3).setPreferredWidth(100);  // Harga
        tabelAturPesanan.getColumnModel().getColumn(4).setPreferredWidth(100);  // Max. Qty
        tabelAturPesanan.getColumnModel().getColumn(5).setPreferredWidth(80);   // Qty
    }

    private void isiTabelPesanan() {
        javax.swing.table.DefaultTableModel modelPesanan
                = new javax.swing.table.DefaultTableModel(
                        new Object[][]{},
                        new String[]{
                            "Kode", "Nama", "Kategori", "Harga", "Max. Qty", "Qty"
                        }
                ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 5; // Hanya kolom Qty yang editable
            }
        };

        for (MenuItem item : pesananDiterima) {
            // Tentukan Max Qty berdasarkan tipe item
            int maxQty;
            if (item instanceof kohisop.model.Makanan) {
                maxQty = kohisop.model.Makanan.MAX_KUANTITAS;
            } else if (item instanceof kohisop.model.Minuman) {
                maxQty = kohisop.model.Minuman.MAX_KUANTITAS;
            } else {
                maxQty = 0;
            }

            modelPesanan.addRow(new Object[]{
                item.getKode(),
                item.getNama(),
                item.getKategori(),
                "Rp" + String.format("%.0f", item.getHarga()),
                maxQty,
                0 // Qty awal 0
            });
        }

        tabelAturPesanan.setModel(modelPesanan);

        // Set editor untuk kolom Qty menggunakan JTextField
        javax.swing.JTextField textField = new javax.swing.JTextField();
        tabelAturPesanan.getColumnModel().getColumn(5).setCellEditor(new javax.swing.DefaultCellEditor(textField));

        setColumnWidths();
    }

    private Member cariMemberByKode(String kode) {
        for (Member m : databaseMember) {
            if (m.getKodeMember().equalsIgnoreCase(kode)) {
                return m;
            }
        }
        return null;
    }

    private double hitungTotalBelanja() {
        double total = 0;
        for (int i = 0; i < tabelAturPesanan.getRowCount(); i++) {
            String hargaStr = tabelAturPesanan.getValueAt(i, 3).toString().replace("Rp", "").trim();

            // Parse qty dari String (karena di-edit pakai JTextField)
            int qty = 0;
            try {
                qty = Integer.parseInt(tabelAturPesanan.getValueAt(i, 5).toString());
            } catch (NumberFormatException e) {
                qty = 0;
            }

            try {
                double harga = Double.parseDouble(hargaStr);
                total += harga * qty;
            } catch (NumberFormatException e) {
                // Skip jika tidak valid
            }
        }
        return total;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Membership.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Membership.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Membership.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Membership.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Membership().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton buttonCariMember;
    private javax.swing.JButton buttonDaftarMember;
    private javax.swing.JButton buttonLanjutkanPembayaran;
    private javax.swing.JButton buttonTambahQty;
    private javax.swing.JButton buttonKurangQty;
    private javax.swing.JCheckBox checkBoxBukanSebagaiMember;
    private javax.swing.JCheckBox checkBoxDaftarMemberBaru;
    private javax.swing.JCheckBox checkBoxPunyaKode;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelAturPesanan;
    private javax.swing.JLabel labelAturQty;
    private javax.swing.JLabel labelMasukkanNama;
    private javax.swing.JLabel labelMembership;
    private javax.swing.JLabel labelPoin;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JTable tabelAturPesanan;
    private javax.swing.JTextArea textAreaMethod;
    private javax.swing.JTextField textFieldMasukkanKode;
    private javax.swing.JTextField textFieldMasukkanNama;
    // End of variables declaration                   
}
