/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kohisop.views;

import java.util.ArrayList;
import javax.swing.JFrame;

import javax.swing.table.DefaultTableModel;

import kohisop.model.entities.MenuItem;
import kohisop.service.MenuService;

/**
 *
 * @author timbu
 */
public class DashboardNew extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    private MenuService menu;
    private ArrayList<MenuItem> daftarPesanan;

    public DashboardNew() {
        initComponents();
        this.menu = new MenuService();
        this.daftarPesanan = new ArrayList<>();
        isiTabelDariMenu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        labelTitle = new javax.swing.JLabel();
        labelSubTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelMinuman = new javax.swing.JTable();
        labelMakanan = new javax.swing.JLabel();
        labelMinuman = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableMakanan = new javax.swing.JTable();
        labelKeranjangPesanan = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelKeranjangPesanan = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        textAreaTotal = new javax.swing.JTextArea();
        labelTotal = new javax.swing.JLabel();
        buttonLanjut = new javax.swing.JButton();
        buttonTambahPesanan = new javax.swing.JButton();
        textFieldMasukkanKode = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitle.setText("KohiSop");

        labelSubTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelSubTitle.setText("Pilihan Menu");

        tabelMinuman.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Kode", "Nama", "Harga"
                }));
        jScrollPane1.setViewportView(tabelMinuman);

        labelMakanan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelMakanan.setText("Makanan");

        labelMinuman.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelMinuman.setText("Minuman");

        tableMakanan.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Kode", "Nama", "Harga"
                }));
        jScrollPane3.setViewportView(tableMakanan);

        labelKeranjangPesanan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelKeranjangPesanan.setText("Keranjang Pesanan");

        tabelKeranjangPesanan.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {null, null, null},
                    {null, null, null},
                    {null, null, null},
                    {null, null, null},
                    {null, null, null},
                    {null, null, null},
                    {null, null, null},
                    {null, null, null},
                    {null, null, null},
                    {null, null, null}
                },
                new String[]{
                    "Kode", "Nama Menu", "Harga"
                }));
        jScrollPane2.setViewportView(tabelKeranjangPesanan);

        textAreaTotal.setColumns(20);
        textAreaTotal.setRows(5);
        jScrollPane4.setViewportView(textAreaTotal);

        labelTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTotal.setText("Total : ");

        buttonLanjut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonLanjut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLanjutActionPerformed(evt);
            }
        });
        buttonLanjut.setText("Lanjut");

        buttonTambahPesanan.setText("Tambah pesanan");
        buttonTambahPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahPesananActionPerformed(evt);
            }
        });

        textFieldMasukkanKode.setText("Masukkan kode disini");
        textFieldMasukkanKode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldMasukkanKodeActionPerformed(evt);
            }
        });

        javax.swing.JPanel mainPanel = new javax.swing.JPanel();
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(labelTitle, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addContainerGap())
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(textFieldMasukkanKode,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        200,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(buttonTambahPesanan)
                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                        .addComponent(labelKeranjangPesanan)
                                                                        .addComponent(labelMakanan)
                                                                        .addComponent(labelSubTitle,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                162,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(labelMinuman)
                                                                        .addComponent(jScrollPane3,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                569, Short.MAX_VALUE)
                                                                        .addComponent(jScrollPane1)
                                                                        .addComponent(jScrollPane2)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(labelTotal,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        114,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        Short.MAX_VALUE)
                                                                                .addComponent(jScrollPane4,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addComponent(buttonLanjut,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE))
                                                                .addContainerGap(15, Short.MAX_VALUE)))))));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 49,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelSubTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelMakanan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 193,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelMinuman)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(buttonTambahPesanan)
                                        .addComponent(textFieldMasukkanKode, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addComponent(labelKeranjangPesanan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 236,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 29,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonLanjut, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)));

        javax.swing.JScrollPane mainScrollPane = new javax.swing.JScrollPane(mainPanel);
        mainScrollPane.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        mainScrollPane.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        setContentPane(mainScrollPane);

        setPreferredSize(new java.awt.Dimension(620, 700));
        pack();
    }// </editor-fold>

    private void isiTabelDariMenu() {
        MenuService menu = new MenuService();

        // --- Isi & Sort Tabel Minuman ---
        ArrayList<MenuItem> daftarMinuman = menu.getDaftarMinuman();
        bubbleSort(daftarMinuman);

        DefaultTableModel modelMinuman = (DefaultTableModel) tabelMinuman.getModel();
        modelMinuman.setRowCount(0);
        for (MenuItem item : daftarMinuman) {
            modelMinuman.addRow(new Object[]{
                item.getKode(),
                item.getNama(),
                "Rp" + String.format("%.2f", item.getHarga())
            });
        }

        // --- Isi & Sort Tabel Makanan ---
        ArrayList<MenuItem> daftarMakanan = menu.getDaftarMakanan();
        bubbleSort(daftarMakanan);

        DefaultTableModel modelMakanan = (DefaultTableModel) tableMakanan.getModel();
        modelMakanan.setRowCount(0);
        for (MenuItem item : daftarMakanan) {
            modelMakanan.addRow(new Object[]{
                item.getKode(),
                item.getNama(),
                "Rp" + String.format("%.2f", item.getHarga())
            });
        }
    }

    

    private void bubbleSort(ArrayList<MenuItem> list) {
        int n = list.size();
        for (int i = 0; i < n - 1; i++) {
            for (int j = 0; j < n - i - 1; j++) {
                if (list.get(j).getHarga() < list.get(j + 1).getHarga()) {
                    MenuItem temp = list.get(j);
                    list.set(j, list.get(j + 1));
                    list.set(j + 1, temp);
                }
            }
        }
    }

    private void updateTotal() {
        double total = 0;
        for (MenuItem item : daftarPesanan) {
            total += item.getHarga();
        }
        textAreaTotal.setText("Rp" + String.format("%.2f", total));
    }

    private void buttonTambahPesananActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String kode = textFieldMasukkanKode.getText().trim();

        if (kode.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Masukkan kode menu terlebih dahulu!",
                    "Peringatan",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        MenuItem item = menu.cariByKode(kode);

        if (item == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Kode menu tidak ditemukan!",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        } else {
            // Tambahkan ke tabel keranjang pesanan
            DefaultTableModel modelKeranjang = (DefaultTableModel) tabelKeranjangPesanan.getModel();
            modelKeranjang.insertRow(0, new Object[]{
                item.getKode(),
                item.getNama(),
                "Rp" + String.format("%.2f", item.getHarga())
            });

            // Simpan ke daftar pesanan
            daftarPesanan.add(0, item);

            updateTotal();

            // Kosongkan textfield
            textFieldMasukkanKode.setText("");

            // Tampilkan sukses
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Pesanan ditambahkan!",
                    "Sukses",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void textFieldMasukkanKodeActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        buttonTambahPesananActionPerformed(null);
    }

    private void buttonLanjutActionPerformed(java.awt.event.ActionEvent evt) {
        Membership membershipFrame = new Membership(daftarPesanan);
        membershipFrame.setVisible(true);
        this.dispose(); // Tutup halaman DashboardNew
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardNew().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton buttonLanjut;
    private javax.swing.JButton buttonTambahPesanan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labelKeranjangPesanan;
    private javax.swing.JLabel labelMakanan;
    private javax.swing.JLabel labelMinuman;
    private javax.swing.JLabel labelSubTitle;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JTable tabelKeranjangPesanan;
    private javax.swing.JTable tabelMinuman;
    private javax.swing.JTable tableMakanan;
    private javax.swing.JTextArea textAreaTotal;
    private javax.swing.JTextField textFieldMasukkanKode;
    // End of variables declaration
}
