/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kohisop.views;

import kohisop.model.membership.Member;
import kohisop.model.entities.MenuItem;
import kohisop.model.entities.ItemPesanan;
import kohisop.model.entities.Pesanan;
import kohisop.model.payment.Tunai;
import kohisop.model.payment.Qris;
import kohisop.model.payment.Emoney;
import kohisop.model.currency.IDR;
import kohisop.model.currency.USD;
import kohisop.model.currency.JPY;
import kohisop.model.currency.MYR;
import kohisop.model.currency.EUR;
import kohisop.model.currency.MataUang;
import kohisop.service.KuitansiService;
import kohisop.service.PembayaranService.HasilPembayaran;
import kohisop.controller.PembayaranController;
import kohisop.app.KohiApp;
import javax.swing.JOptionPane;
import java.util.ArrayList;

/**
 *
 * @author timbu
 */
public class Pembayaran extends javax.swing.JFrame {

    /**
     * Creates new form Pembayaran
     */
    private Member currentMember;
    private ArrayList<ItemPesanan> pesananItems;
    private double totalBelanja;
    private boolean transaksiSudahDiproses;
    private MataUang selectedCurrency = new IDR();
    private kohisop.model.payment.MetodePembayaran selectedPaymentMethod = new Tunai();
    
    // MVC: Controller
    private PembayaranController controller;

    public Pembayaran() {
        this(null, new ArrayList<>(), 0);
    }

    public Pembayaran(Member currentMember, ArrayList<ItemPesanan> pesananItems, double totalBelanja) {
        this.currentMember = currentMember;
        this.pesananItems = pesananItems;
        this.totalBelanja = totalBelanja;
        this.transaksiSudahDiproses = false;
        this.selectedCurrency = new IDR();
        this.selectedPaymentMethod = new Tunai();
        
        // Initialize Controller
        this.controller = new PembayaranController();
        this.controller.setDataPembayaran(currentMember, pesananItems, totalBelanja);
        
        initComponents();
        updateKuitansiPreview();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        mainScrollPane = new javax.swing.JScrollPane();
        mainPanel = new javax.swing.JPanel();
        labelMetodePembayaran = new javax.swing.JLabel();
        labelTitle = new javax.swing.JLabel();
        checkBoxTunai = new javax.swing.JCheckBox();
        checkBoxQRIS = new javax.swing.JCheckBox();
        checkBoxEMoney = new javax.swing.JCheckBox();
        labelMataUang = new javax.swing.JLabel();
        checkBoxIDR = new javax.swing.JCheckBox();
        checkBoxUSD = new javax.swing.JCheckBox();
        checkBoxJPY = new javax.swing.JCheckBox();
        checkBoxMYR = new javax.swing.JCheckBox();
        checkBoxEUR = new javax.swing.JCheckBox();
        labelSaldo = new javax.swing.JLabel();
        textFieldSaldo = new javax.swing.JTextField();
        labelKuitansi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaKuitansi = new javax.swing.JTextArea();
        buttonProsesPembayaran = new javax.swing.JButton();
        buttonPelangganBaru = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelMetodePembayaran.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelMetodePembayaran.setText("Metode Pembayaran");

        labelTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitle.setText("KohiSop");

        checkBoxTunai.setText("Tunai (Tanpa Diskon)");
        checkBoxTunai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxTunaiActionPerformed(evt);
            }
        });

        checkBoxQRIS.setText("QRIS (Diskon 5%)");
        checkBoxQRIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxQRISActionPerformed(evt);
            }
        });

        checkBoxEMoney.setText("eMoney (Diskon 7% - Biaya Admin Rp.20) ");
        checkBoxEMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxEMoneyActionPerformed(evt);
            }
        });

        labelMataUang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelMataUang.setText("Mata Uang");

        checkBoxIDR.setText("IDR");
        checkBoxIDR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxIDRActionPerformed(evt);
            }
        });

        checkBoxUSD.setText("USD (1 USD =15 IDR)");
        checkBoxUSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxUSDActionPerformed(evt);
            }
        });

        checkBoxJPY.setText("JPY (10 JPY = 1 IDR)");
        checkBoxJPY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxJPYActionPerformed(evt);
            }
        });

        checkBoxMYR.setText("MYR (1 MYR = 4 IDR)");
        checkBoxMYR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxMYRActionPerformed(evt);
            }
        });

        checkBoxEUR.setText("EUR (1 EUR = 14 IDR)");
        checkBoxEUR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxEURActionPerformed(evt);
            }
        });

        labelSaldo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelSaldo.setText("Saldo Anda");
        labelSaldo.setVisible(false);

        textFieldSaldo.setText("0");
        textFieldSaldo.setVisible(false);

        labelKuitansi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelKuitansi.setText("Kuitansi");

        textAreaKuitansi.setColumns(20);
        textAreaKuitansi.setRows(5);
        jScrollPane1.setViewportView(textAreaKuitansi);

        buttonProsesPembayaran.setText("Proses Pembayaran");
        buttonProsesPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProsesPembayaranActionPerformed(evt);
            }
        });

        buttonPelangganBaru.setText("Pelanggan Baru");
        buttonPelangganBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPelangganBaruActionPerformed(evt);
            }
        });

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
                mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(labelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addGroup(mainPanelLayout.createSequentialGroup()
                                                                        .addComponent(checkBoxTunai)
                                                                        .addGap(180, 180, 180))
                                                                .addComponent(labelMetodePembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(checkBoxEMoney)
                                                                        .addComponent(checkBoxQRIS))
                                                                .addGap(0, 0, Short.MAX_VALUE)))
                                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(labelMataUang, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(checkBoxIDR)
                                                        .addComponent(checkBoxUSD)
                                                        .addComponent(checkBoxJPY)
                                                        .addComponent(checkBoxMYR)
                                                        .addComponent(checkBoxEUR)))
                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                                .addComponent(labelSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textFieldSaldo))
                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                                .addComponent(labelKuitansi, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                                .addComponent(buttonProsesPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(buttonPelangganBaru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
                mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelMetodePembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(labelMataUang, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(checkBoxTunai)
                                        .addComponent(checkBoxIDR))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(checkBoxQRIS)
                                        .addComponent(checkBoxUSD))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(checkBoxEMoney)
                                        .addComponent(checkBoxJPY))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkBoxMYR)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkBoxEUR)
                                .addGap(28, 28, 28)
                                .addComponent(labelSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelKuitansi, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(buttonProsesPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(buttonPelangganBaru, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(20, Short.MAX_VALUE))
        );

        mainScrollPane.setViewportView(mainPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mainScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mainScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>
    

    private void checkBoxTunaiActionPerformed(java.awt.event.ActionEvent evt) {
        uncheckOtherPaymentMethods(checkBoxTunai);
        selectedPaymentMethod = new Tunai();
        labelSaldo.setText("Saldo Anda");
        labelSaldo.setVisible(true);
        textFieldSaldo.setVisible(true);
        updateKuitansiPreview();
    }

    private void checkBoxQRISActionPerformed(java.awt.event.ActionEvent evt) {
        uncheckOtherPaymentMethods(checkBoxQRIS);
        selectedPaymentMethod = new Qris(Double.MAX_VALUE);
        labelSaldo.setText("Saldo QRIS");
        labelSaldo.setVisible(true);
        textFieldSaldo.setVisible(true);
        updateKuitansiPreview();
    }

    private void checkBoxEMoneyActionPerformed(java.awt.event.ActionEvent evt) {
        uncheckOtherPaymentMethods(checkBoxEMoney);
        selectedPaymentMethod = new Emoney(Double.MAX_VALUE);
        labelSaldo.setText("Saldo E-Money");
        labelSaldo.setVisible(true);
        textFieldSaldo.setVisible(true);
        updateKuitansiPreview();
    }

    private void checkBoxIDRActionPerformed(java.awt.event.ActionEvent evt) {
        uncheckOtherCurrencies(checkBoxIDR);
        selectedCurrency = new IDR();
        updateKuitansiPreview();
    }

    private void checkBoxUSDActionPerformed(java.awt.event.ActionEvent evt) {
        uncheckOtherCurrencies(checkBoxUSD);
        selectedCurrency = new USD();
        updateKuitansiPreview();
    }

    private void checkBoxJPYActionPerformed(java.awt.event.ActionEvent evt) {
        uncheckOtherCurrencies(checkBoxJPY);
        selectedCurrency = new JPY();
        updateKuitansiPreview();
    }

    private void checkBoxMYRActionPerformed(java.awt.event.ActionEvent evt) {
        uncheckOtherCurrencies(checkBoxMYR);
        selectedCurrency = new MYR();
        updateKuitansiPreview();
    }

    private void checkBoxEURActionPerformed(java.awt.event.ActionEvent evt) {
        uncheckOtherCurrencies(checkBoxEUR);
        selectedCurrency = new EUR();
        updateKuitansiPreview();
    }

    private void uncheckOtherPaymentMethods(javax.swing.JCheckBox selected) {
        if (selected != checkBoxTunai) {
            checkBoxTunai.setSelected(false);
        }
        if (selected != checkBoxQRIS) {
            checkBoxQRIS.setSelected(false);
        }
        if (selected != checkBoxEMoney) {
            checkBoxEMoney.setSelected(false);
        }
    }

    private void uncheckOtherCurrencies(javax.swing.JCheckBox selected) {
        if (selected != checkBoxIDR) {
            checkBoxIDR.setSelected(false);
        }
        if (selected != checkBoxUSD) {
            checkBoxUSD.setSelected(false);
        }
        if (selected != checkBoxJPY) {
            checkBoxJPY.setSelected(false);
        }
        if (selected != checkBoxMYR) {
            checkBoxMYR.setSelected(false);
        }
        if (selected != checkBoxEUR) {
            checkBoxEUR.setSelected(false);
        }
    }

    private void updateKuitansiPreview() {
        if (pesananItems.isEmpty()) {
            textAreaKuitansi.setText("Tidak ada item pesanan");
            return;
        }

        Pesanan pesanan = new Pesanan();
        if (currentMember != null) {
            pesanan.setMember(currentMember);
        }

        for (ItemPesanan item : pesananItems) {
            pesanan.tambahItem(item);
        }

        int poinSebelum = currentMember != null ? currentMember.getPoin() : 0;
        int poinDidapat = (int) (totalBelanja / 10);
        if (currentMember != null && currentMember.isPoinGanda()) {
            poinDidapat *= 2;
        }

        KuitansiService kuitansi = new KuitansiService(pesanan, selectedPaymentMethod, selectedCurrency, 0, poinSebelum, poinDidapat);
        textAreaKuitansi.setText(kuitansi.generate());
    }

    private void buttonProsesPembayaranActionPerformed(java.awt.event.ActionEvent evt) {
        if (transaksiSudahDiproses) {
            JOptionPane.showMessageDialog(this, "Transaksi ini sudah diproses!", "Info", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        // Get selected payment method
        kohisop.model.payment.MetodePembayaran metodePembayaran = null;
        if (checkBoxTunai.isSelected()) {
            metodePembayaran = new Tunai();
        } else if (checkBoxQRIS.isSelected()) {
            metodePembayaran = new Qris(0);
        } else if (checkBoxEMoney.isSelected()) {
            metodePembayaran = new Emoney(0);
        }

        // Get selected currency
        MataUang mataUang = null;
        if (checkBoxIDR.isSelected()) {
            mataUang = new IDR();
        } else if (checkBoxUSD.isSelected()) {
            mataUang = new USD();
        } else if (checkBoxJPY.isSelected()) {
            mataUang = new JPY();
        } else if (checkBoxMYR.isSelected()) {
            mataUang = new MYR();
        } else if (checkBoxEUR.isSelected()) {
            mataUang = new EUR();
        }

        // Gunakan controller untuk proses pembayaran
        HasilPembayaran hasil = controller.prosesPembayaran(textFieldSaldo.getText(), metodePembayaran, mataUang);

        if (!hasil.berhasil) {
            // Tampilkan error
            JOptionPane.showMessageDialog(this, hasil.pesan, "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            // Update kuitansi display
            textAreaKuitansi.setText(hasil.kuitansi);
            transaksiSudahDiproses = true;
            
            // Tampilkan pesan sukses
            JOptionPane.showMessageDialog(this, hasil.pesan, "Sukses", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void buttonPelangganBaruActionPerformed(java.awt.event.ActionEvent evt) {
        // Kembali ke DashboardNew
        DashboardNew dashboard = new DashboardNew();
        dashboard.setVisible(true);
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton buttonPelangganBaru;
    private javax.swing.JButton buttonProsesPembayaran;
    private javax.swing.JCheckBox checkBoxEMoney;
    private javax.swing.JCheckBox checkBoxEUR;
    private javax.swing.JCheckBox checkBoxIDR;
    private javax.swing.JCheckBox checkBoxJPY;
    private javax.swing.JCheckBox checkBoxMYR;
    private javax.swing.JCheckBox checkBoxQRIS;
    private javax.swing.JCheckBox checkBoxTunai;
    private javax.swing.JCheckBox checkBoxUSD;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelKuitansi;
    private javax.swing.JLabel labelMataUang;
    private javax.swing.JLabel labelMetodePembayaran;
    private javax.swing.JLabel labelSaldo;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JTextArea textAreaKuitansi;
    private javax.swing.JTextField textFieldSaldo;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JScrollPane mainScrollPane;
    // End of variables declaration                   
}
